Make Created At correspond to actual creation date and add Modified At.
lektor/lektor pull request #274
Opened 2016-09-04 02:25 UTC by alecbrooks

I noticed that the created_at image item didn't seem to correspond to the actual date the photograph was taken, so I modified the property to use the correct EXIF field. I also added a modified_at item.

2016-10-26 00:23 UTC, singingwolfboy requested changes
Can you point me to some documentation about EXIF information? I don't know how to determine if your pull request is correct or not.

2016-10-26 00:23 UTC, singingwolfboy commented on lektor/imagetools.py
> +            print(self._mapping)
This pull request can't be merged with debugging statements like this still in the code.

2016-10-26 00:23 UTC, singingwolfboy commented on tests/test_images.py
> +    assert image.exif.modified_at == datetime(2015, 12, 6, 11, 37, 34)
Thanks for the test! 💖

2016-11-02 01:35 UTC, alecbrooks commented
According to its readme, EXIFRead uses the official tag names. Referring to the [2.3 EXIF spec](http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf) entries for the tags, 
* DateTimeOriginal is "The date and time when the original image data was generated. " (pg. 48 or 53 in the file)
* DateTime is "The date and time of image creation. In this standard it is the date and time the file was changed. " (pg. 38 or 44 in the file) That's more ambiguous than I realized. It looks like the original TIFF format used the same [tag](http://www.awaresystems.be/imaging/tiff/tifftags/datetime.html) for the image creation date, but EXIF now uses it for the modification date.

Lektor doesn't have special handling for TIFF, so I think we're okay to use DateTime as date modified. I could look into whether it makes sense to do something more complicated, e.g., using DateTime as date created if DateTimeOriginal is missing.

2017-02-17 03:38 UTC, tariquesani commented
Created at has been fixed via https://github.com/lektor/lektor/pull/276 closing this for now. Can be reopened if conflicts  are resolved and changes requested done.

2017-02-17 03:38 UTC, closed without merging